# Default properties
configFile:
credentialsDir:
testSuiteDescription:
target:
feature:
  mappings:
    - null

# Logging
quarkus:
  log:
    level: INFO
    category:
      "com.intuit.karate":
        level: DEBUG
      "org.solid.testharness":
        level: INFO
