# Default logging
quarkus:
  log:
    level: INFO
    category:
      "com.intuit.karate":
        level: INFO
      "org.solid.testharness":
        level: INFO
    json:
      console:
        enable: false
  index-dependency:
    armeria:
      group-id: com.linecorp.armeria
      artifact-id: armeria
    netty-buffer:
      group-id: io.netty
      artifact-id: netty-buffer
    netty-common:
      group-id: io.netty
      artifact-id: netty-common