subjects: /data/test-subjects.ttl
sources:
  - /data/protocol/solid-protocol-test-manifest.ttl
  - /data/web-access-control/web-access-control-test-manifest.ttl
  - /data/protocol/solid-protocol-spec.ttl
  - /data/web-access-control/web-access-control-spec.ttl
target: https://github.com/solid/conformance-test-harness/css
mappings:
  - prefix: https://github.com/solid/specification-tests/
    path: /data/
