subjects: /data/test-subjects.ttl
sources:
  - https://github.com/solid/specification-tests/protocol/solid-protocol-test-manifest.ttl
  - https://github.com/solid/specification-tests/web-access-control/web-access-control-test-manifest.ttl
  - https://solidproject.org/TR/protocol
  - https://github.com/solid/specification-tests/web-access-control/web-access-control-spec.ttl
#  - https://github.com/solid/specification-tests/protocol/converted.ttl
target: ess
mappings:
  - prefix: https://github.com/solid/specification-tests/
    path: /data
